# Generated by Django 5.0.6 on 2024-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_buyinfo_cartinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
