# Generated by Django 5.0.6 on 2024-06-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cartinfo_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('caddress', models.CharField(max_length=255)),
                ('cpincode', models.CharField(max_length=255)),
                ('cmobile', models.CharField(max_length=255)),
                ('cquantity', models.CharField(max_length=255)),
                ('ctotalwithoutgst', models.CharField(max_length=255)),
                ('ctotalwithgst', models.CharField(max_length=255)),
            ],
        ),
    ]
